version: '3.7'

services:
  nginx:
    image: nginx:1.16.1
    container_name: tn_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
     #  - ./conf/nginx/local.crt:/var/www/ssl/local.crt
     #  - ./conf/nginx/local.key:/var/www/ssl/local.key
     #  - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
     #  - ${PROJECT_PATH}:/var/www/html
    networks:
      - app

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      # seeding scripts
      - ./mongodb/mongo-entrypoint:/docker-entrypoint-initdb.d
      # named volumes
      - ./mongodb/data/db:/data/db
      - ./mongodb/data/configdb:/data/configdb
    networks:
      - app

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
    networks:
      - app

networks:
  app:
    driver: bridge